name: CALS
favicon: null
layout_spectrum: 0.7409078921191394
typography_spectrum: 0.6630794734228402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3681779499165714
  lightness: 0.18047734559513628
  saturation: 0.8978382048662752
  rhythmicContrast: 0.8731376719661057
purpose: []
